on:
  push:
    branches:
      - '**'

name: CI

jobs:
  ci:
    name: Lint check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint check
        id: lint-check
        run: |
          npm install
          npm run lint:check
      - name: Typescript check
        id: type-check
        run: |
          npm run type:check
